# -*- coding: utf-8 -*-
"""despliegue_corazon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hTb2T566b0XKQDKn_qHZ7wGeNuD_2Gov
"""

!pip install streamlit

# Importamos las librerías principales

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle
import streamlit as st

filename = 'modelo-class.pkl'

modelo, labelencoder, variables, min_max_scaler = pickle.load(
    open(filename, 'rb')
)

print("Modelo cargado correctamente.")
print("Variables utilizadas por el modelo:")
print(variables)

# Mostramos las variables que necesita el modelo

print("Variables del modelo:")
for variable in variables:
    print("-", variable)

# Configuración de la página

st.set_page_config(
    page_title="Predicción de ataque al corazón",
    page_icon="🫀",
    layout="wide"
)

# Diseño personalizado

st.markdown("""
<style>

body {
    font-family: Arial, sans-serif;
}

/* Título principal */
.titulo {
    font-size: 42px;
    font-weight: bold;
    color: #B71C1C;
    text-align: center;
    margin-bottom: 5px;
}

/* Subtítulo */
.subtitulo {
    font-size: 18px;
    color: #555555;
    text-align: center;
    margin-bottom: 30px;
}

/* Tarjetas */
.card {
    background-color: #FFFFFF;
    padding: 25px;
    border-radius: 18px;
    border: 1px solid #E5E5E5;
    box-shadow: 0px 4px 12px rgba(0,0,0,0.08);
    margin-bottom: 20px;
}

/* Encabezados */
.seccion {
    color: #B71C1C;
    font-size: 25px;
    font-weight: bold;
    margin-bottom: 15px;
}

/* Resultado */
.resultado {
    background-color: #FFF3F3;
    border-radius: 18px;
    padding: 30px;
    text-align: center;
    border: 2px solid #EF9A9A;
}

.resultado-titulo {
    color: #B71C1C;
    font-size: 24px;
    font-weight: bold;
}

</style>
""", unsafe_allow_html=True)

#encabezado
st.markdown(
    '<div class="titulo">🫀 Predicción de ataque al corazón</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitulo">'
    'Sistema de predicción basado en Machine Learning'
    '</div>',
    unsafe_allow_html=True
)

st.markdown("""
<div class="card">

<div class="seccion">¿Cómo funciona?</div>

<p>
El sistema recibe información del paciente, prepara los datos
y los procesa mediante un modelo de clasificación KNN.
</p>

<p>
El modelo genera una predicción a partir de las características
ingresadas por el usuario.
</p>

</div>
""", unsafe_allow_html=True)

#info. paciente
st.markdown(
    '<div class="seccion">👤 Información del paciente</div>',
    unsafe_allow_html=True
)

col1, col2 = st.columns(2)

with col1:
    age = st.number_input(
        "Edad",
        min_value=1,
        max_value=120,
        value=40,
        step=1
    )

with col2:
    avg_glucose_level = st.number_input(
        "Nivel promedio de glucosa",
        min_value=0.0,
        max_value=300.0,
        value=100.0,
        step=0.1
    )

col1, col2 = st.columns(2)

with col1:

    hypertension = st.selectbox(
        "¿Tiene hipertensión?",
        ["No", "Sí"]
    )

    heart_disease = st.selectbox(
        "¿Tiene enfermedad cardíaca?",
        ["No", "Sí"]
    )

with col2:

    ever_married = st.selectbox(
        "¿Se ha casado alguna vez?",
        ["No", "Sí"]
    )

    smoking_status = st.selectbox(
        "Estado de tabaquismo",
        [
            "never smoked",
            "formerly smoked",
            "smokes"
        ]
    )

# Creamos un DataFrame con los datos ingresados

datos = [[
    age,
    hypertension,
    heart_disease,
    ever_married,
    avg_glucose_level,
    smoking_status
]]

data = pd.DataFrame(
    datos,
    columns=[
        'age',
        'hypertension',
        'heart_disease',
        'ever_married',
        'avg_glucose_level',
        'smoking_status'
    ]
)

data

# Copiamos los datos originales

data_preparada = data.copy()

# Convertimos las variables categóricas en variables dummy

data_preparada = pd.get_dummies(
    data_preparada,
    columns=[
        'smoking_status',
        'hypertension',
        'heart_disease',
        'ever_married'
    ],
    drop_first=True,
    dtype=int
)

data_preparada

# Organizamos las columnas exactamente como las espera el modelo

data_preparada = data_preparada.reindex(
    columns=variables,
    fill_value=0
)

data_preparada

#normalizar
variables_numericas = ['age', 'avg_glucose_level']

# Normalizamos las variables numéricas

data_preparada[['age', 'avg_glucose_level']] = (
    min_max_scaler.transform(
        data_preparada[['age', 'avg_glucose_level']]
    )
)

data_preparada

# Realizamos la predicción

Y_pred = modelo.predict(data_preparada)

print("Predicción codificada:", Y_pred)

# Convertimos la predicción numérica a su etiqueta original

resultado = labelencoder.inverse_transform(Y_pred)

print("Resultado:", resultado[0])

st.markdown(
    '<div class="seccion">🔍 Resultado de la predicción</div>',
    unsafe_allow_html=True
)

st.markdown(
    f"""
    <div class="resultado">

        <div class="resultado-titulo">
            🫀 Resultado
        </div>

        <br>

        <div style="font-size: 30px; font-weight: bold;">
            {resultado[0]}
        </div>

    </div>
    """,
    unsafe_allow_html=True
)

st.markdown("""
<div class="card">

<div class="seccion">🤖 Información del modelo</div>

<p><b>Modelo:</b> K-Nearest Neighbors (KNN)</p>

<p><b>Tipo:</b> Clasificación</p>

<p><b>Preprocesamiento:</b> Variables categóricas + normalización Min-Max</p>

<p><b>Entrenamiento final:</b> 100% de los datos</p>

</div>
""", unsafe_allow_html=True)